config/routes.rb
Rails.application.routes.draw do
  mount RailsSettingsUi::Engine, at: 'settings'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :articles
  resources :articles do
    resources :comments
  end

  root 'articles#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    p user
    if user.has_role? :admin
      p "admin"
      #can :manage, Article
      can :manage, :all
    else
      p "user"
      can :read, :all
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_taggable
  acts_as_taggable_on :tags

  has_many :comments, dependent: :destroy

  validates :title, presence: true,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 5 }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/settings.rb
class Settings < RailsSettings::CachedSettings
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable,
         :omniauthable, :omniauth_providers => [:github,:qq_connect, :weibo]

  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      email = auth.info.email
      user.email = email || user.uid.to_s + "@wilsonblog.com"

      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :queryArticles
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def queryArticles
    @key_word = params[:key_word]
    @tag = params[:tag]

    if (@key_word)
      @articles  = Article.where("text like ? or title like ?", "%" + params[:key_word] + "%", "%" + params[:key_word] + "%").order(updated_at: :desc).page(params[:page]).per(Settings.page_size)
    elsif(@tag)
      @articles = Article.tagged_with(@tag).page(params[:page]).per(Settings.page_size)
    else
      @articles = Article.page(params[:page]).per(Settings.page_size).order(updated_at: :desc)
    end
    @hot_comments = Comment.order(updated_at: :desc).limit(Settings.hot_comments_size)

    @hot_articles = Article.order(view_count: :desc).limit(Settings.hot_articles_size)
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      if User.count == 1
        resource.add_role 'admin'
      end
      resource
    end
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password,
                                                            :password_confirmation, :remember_me, :avatar, :avatar_cache) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password,
                                                                   :password_confirmation, :current_password, :avatar, :avatar_cache) }
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  layout 'blog'

  def index
    respond_to do |format|
      format.html
      format.rss { @articles = Article.all() }
    end
  end

  def new
    @article = Article.new
  end

  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)

    if @article.save
     redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  def show
    @article = Article.find(params[:id])
    currentViewCount = @article.view_count || 0

    logger.info "currentViewCount: " + currentViewCount.to_s
    @article.update(view_count: currentViewCount+1)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :tag_list, :tag_list => [])
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        processResponse
    end

    def weibo
        processResponse
    end

    def qq_connect
        processResponse
    end

    def processResponse
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end

    def sign_out
        sign_out @user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])

    requestParams = comment_params()
    requestParams[:commenter] = current_user.email

    @comment = @article.comments.create(requestParams)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
        :autolink => true,
        :space_after_headers => true,
        :fenced_code_blocks => true,
        :no_intra_emphasis => true,
        :hard_wrap => true,
        :strikethrough =>true
    }
    markdown = Redcarpet::Markdown.new(HTMLwithCodeRay,options)
    markdown.render(h(text)).html_safe
  end

  class HTMLwithCodeRay < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div(:tab_width=>2)
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/application/_footer.html.erb
<footer id="zan-footer">
  <div class="container">
    Copyright © 2015
  </div>
</footer>

app/views/application/_header.html.erb
<div class="ui  large inverted main menu" >
  <div id="mymenu">
    <a class="active green item">
      <i class="large china flag"></i>
    </a>
  </div>
</div>

<header id="zan-header" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="#"><div
      class="navbar-brand"></div></a>
      <button class="navbar-toggle" type="button" data-toggle="collapse"
              data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span> <span
      class="fa fa-reorder fa-lg"></span>
      </button>
    </div>
    <nav class="navbar-collapse bs-navbar-collapse collapse">
      <ul id="menu-navbar" class="nav navbar-nav">
        <li id="menu-item-215"
            class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-215">

          <%= link_to  articles_path, class: "fa fa-home",title:"首页" do %>
              首页
          <%end%>

        </li>
        <li id="menu-item-676"
            class="dropdown menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-676"><a><i
        class="fa fa-cog"></i> Wilson's BLog</a>
        </li>

        <li id="menu-item-676">
            <%= link_to  "/articles.rss", class: "fa fa-rss",title:"RSS订阅" do %>
                RSS订阅
            <%end%>
        </li>

        <% if user_signed_in? %>
            <li id="menu-item-676"
                class="dropdown menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-676"><a><i
            class="fa fa-user"></i> 欢迎你 <%= current_user.email %></a>
            </li>

            <li id="menu-item-676"
                class="dropdown menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-676">
              <%= link_to  "/admin", class: "fa fa-user-md",title:"admin" do %>
                  后台管理
              <%end%>
            </li>

            <li id="menu-item-676"
                class="dropdown menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-676">
              <%= link_to  destroy_user_session_path, method: :delete, class: "ui item" do %>
                  <i class= "fa fa-sign-out"></i>注销
              <%end%>
            </li>
        <% else %>
        <% end %>


    </nav>
  </div>
  <div id="if-fixed" class="pull-right visible-lg visible-md">
    <i class="fa fa-thumb-tack"></i>
    <div class="icheckbox_flat-red checked" style="position: relative;">
      <input type="checkbox" style="position: absolute; opacity: 0;">
      <ins class="iCheck-helper"
           style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins>
    </div>
  </div>
</header>

app/views/articles/_form.html.erb
<%= link_to articles_path do %>
    <i class="fa fa-mail-reply"></i>返回文章列表
<%end%>
<%= form_for @article,class:"form-horizontal" do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="control-group" style="margin-top: 10px">
      <label class="control-label" for="inputEmail"><i class="fa fa-paperclip"></i>标题</label>
      <div class="controls">
        <%= f.text_field :title, size:120 %>
      </div>
    </div>

    <div class="control-group" style="margin-top: 10px">
      <label class="control-label" for="inputEmail"><i class="fa fa-paperclip"></i>标签（*多个标签以","隔开）</label>
      <div class="controls">
        <%= f.text_field :tag_list,:size=>'120' %>
      </div>
    </div>

    <div class="control-group" style="margin-top: 10px">
      <label class="control-label" for="inputEmail"><i class="fa fa-list-alt"></i>正文(支持Markdown)</label>
      <div class="controls">
        <%= f.text_area :text,rows:"30", cols:"120" %>
      </div>
    </div>

    <div class="control-group" style="margin-top: 10px">
      <div class="controls">
        <%= f.submit "发布", class: "btn btn-success"%>
      </div>
    </div>

<% end %>

app/views/articles/edit.html.erb
<div class="ui segment">
  <h3 class="ui dividing header"><i class="edit icon"></i>编辑
  </h3>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
  <!-- 轮播（Carousel）指标 -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- 轮播（Carousel）项目 -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("car_1.jpg", size: "750x300", alt: "car1", class:"attachment-full wp-post-image") %>
    </div>
    <div class="item">
      <%= image_tag("car_2.jpg", size: "750x300", alt: "car2", class:"attachment-full wp-post-image") %>
    </div>
    <div class="item">
      <%= image_tag("car_3.jpg", size: "750x300", alt: "car3", class:"attachment-full wp-post-image") %>
    </div>
  </div>
  <!-- 轮播（Carousel）导航 -->
  <a class="carousel-control left" href="#myCarousel"
     data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel"
     data-slide="next">&rsaquo;</a>
</div>

<% @articles.each do |article| %>
    <div id="article-list">
      <div class="article well clearfix">
        <i class="fa fa-bookmark article-stick visible-md visible-lg"></i>
        <div class="data-article hidden-xs">
          <span class="month"><%= article.created_at.strftime("%m") %>月</span> <span class="day"><%= article.created_at.strftime("%d") %></span>
        </div>

        <section class="hidden-xs">

          <div class="title-article">
            <h1>
              <%= link_to article.title, article_path(article),id: "myTitle" %>
            </h1>
          </div>
          <div class="tag-article">
            <span class="label label-zan">

              <% article.tag_list.each do |info_tag| %>
                <i class="fa fa-tags"></i>
                <span><a href="#" rel="category tag"><%= info_tag %>  </a></span>
              <% end %>

              <span class="label label-zan">
              <i class="fa fa-user"></i><i class="fa fa-eye"></i>
             <%= article.view_count%>
            </span>
          </div>


          <div class="content-article">
              <blockquote>
                <%= markdown(article.text.truncate(200).html_safe) %>
              </blockquote>
          </div>

          <%= link_to  article_path(article), class: "btn btn-danger pull-right read-more" do %>
              阅读全文<span class="badge"><%= article.view_count%></span>
          <%end%>
        </section>

      </div>

    </div>
    <!-- 内容主体结束 -->
<% end %>
<!-- 分页 -->

<div id="zan-page" class="clearfix">
  <ul class="pagination pagination-zan pull-right">
    <%= paginate @articles, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm"%>
  </ul>
</div>
<!-- 分页结束 -->

app/views/articles/index.rss.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>wilsonsblog</title>
    <description>蔡稳的博客</description>
    <link>http://wilsonsblog.herokuapp.com/</link>
    <language>zh-CN</language>
    <copyright>Copyright 2015, wilson.com</copyright>
    <docs>http://blogs.law.harvard.edu/tech/rss</docs>
    <atom:link href="http://wilsonsblog.herokuapp.com/articles.rss" rel=" self " type="application/rss+xml"/>
    <% @articles.each do |article| %>
        <item>
          <title><%= article.title %></title>
          <description>
            <![CDATA[ <%= article.text.html_safe %> ]]>
          </description>
          <pubDate><%= article.created_at.rfc822 %></pubDate>
          <link><%= article_url(article) %></link>
          <guid isPermaLink="false"><%= article_url(article) %></guid>
        </item>
    <% end %>
  </channel>
</rss>

app/views/articles/new.html.erb
  <aside id="zan_hotest_posts-2">
    <div class="panel panel-zan hot hidden-xs">
      <div class="panel-heading">

        <i class="fa fa-file"></i>发帖 <i class="fa fa-times-circle panel-remove"></i> <i class="fa fa-chevron-circle-up panel-toggle"></i>

      </div>

      <div style="margin: 20px">
      <%= render 'form' %>
      </div>
    </div>
  </aside>

app/views/articles/show.html.erb
<article class="article container well">

  <!-- 面包屑 -->
  <div class="breadcrumb">
    <i class="fa fa-hom		e"></i>

    <%= link_to  articles_path, class: "home" do %>
        博客
    <%end%>/
    <%= @article.title %>

    <div style="float: right">

    <%= link_to  edit_article_path(@article), class: "home" do %>
        <i class="fa fa-tags"></i>编辑
    <%end%>

    <%= link_to article_path(@article),
                method: :delete,
                data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-minus-square"></i>删除
    <%end%>
    </div>
  </div>
  <!-- 面包屑结束 -->

  <div class="hidden-xs">
    <div class="title-article">
      <h1>
        <a href="#"><%= @article.title %></a>
      </h1>
    </div>
    <div class="tag-article container">
								<span class="label label-zan"><i class="fa fa-tags"></i>
									9-21</span>

      <% @article.tag_list.each do |info_tag| %>
          <span> <i class="fa fa-tags"></i><%= info_tag %> </span>
      <% end %>

    </div>
  </div>

  <div class="centent-article">
    <figure class="thumbnail hidden-xs"><%= image_tag("car_3.jpg", size: "750x300", alt: "car3", class:"attachment-full wp-post-image") %></figure>

    <p> <%= markdown(@article.text.html_safe) %></p>
    <!-- 分页 -->
    <div class="zan-page bs-example">
      <ul class="pager">
        <li class="previous"><a href="#" rel="prev">上一篇</a></li>
        <li class="next"><a href="#" rel="next">下一篇</a></li>
      </ul>
    </div>
    <!-- 分页 -->

    <!-- 文章版权信息 -->
    <div class="copyright alert alert-success">
      <p>
        版权属于: <a href="http://www.yeahzan.com/zanblog">Wilson</a>
      </p>
      <p>
        原文地址: <a href="#"><%= link_to @article.title, article_path(@article),id: "myTitle" %></a>
      </p>
      <p>转载时必须以链接形式注明原始出处及本声明。</p>
    </div>
  </div>
</article>

<%= render(:partial=>'comments/comments') %>

app/views/comments/_comments.html.erb
<div id="comments-template">
  <div class="comments-wrap">
    <div id="comments">
      <h3 id="comments-title" class="comments-header alert alert-info"><i class="fa fa-comments"></i> <%= @article.comments.size %> 条评论</h3>
      <div id="loading-comments"><i class="fa fa-spinner fa-spin"></i></div>

      <ol class="commentlist">
        <% @article.comments.each do |comment| %>

            <li id="comment-2127" class="comment byuser comment-author-wuyuyuan even thread-even depth-1">
              <article id="div-comment-2127" class="comment-body">
                <footer class="comment-meta">
                  <div class="comment-author vcard">
                    <img alt="" src="http://cn.gravatar.com/avatar/5f3ec2c2e67799398424e2357827e6fa?s=70&amp;d=monsterid&amp;r=G" class="avatar avatar-70 photo" height="70" width="70">
                    <b class="fn"><a href="#" rel="external nofollow" class="url"><%= comment.commenter %></a></b>
                    <span class="says">说道：</span>
                  </div>

                  <div class="comment-metadata">
                    <a href="#">
                      <time datetime="2015-01-09T22:27:01+00:00">
                        <%= time_ago_in_words(comment.created_at) %>							</time>
                    </a>
                  </div>

                </footer>

                <div class="comment-content">
                  <p> <%= comment.body %></p>
                </div>
              </article>
            </li>
        <% end %>

    </div>

    <h3 id="reply-title" class="comment-reply-title"><i class="fa fa-pencil"></i> 欢迎留言 </h3>
    <div id="respond" class="comment-respond">
      <%= form_for([@article, @article.comments.build],  html: { class: "comment-form", id: "commentform" } ) do |f| %>
          <%= f.text_area :body, rows:"10", cols:"4",placeholder:"赶快发表你的见解吧！"  %>
          <p class="form-submit">
            <%= f.submit "发表评论", class: "ui green button", id:"submit"%>
          </p>
      <% end %>
    </div><!-- #respond -->

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wilson's BLog</title>
  <meta property="qc:admins" content="771157112437632477605273510063757" />
  <meta property="wb:webmaster" content="edd4773606fbeece" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="home blog nav-fixed">


<div id="zan-bodyer">
  <div class="container">

    <div class="row">
      <div  class="col-md-4 col-sm-offset-4">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wilson's BLog</title>
  <meta property="qc:admins" content="771157112437632477605273510063757" />
  <meta property="wb:webmaster" content="edd4773606fbeece" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="home blog nav-fixed">
<%= render(:partial=>'header') %>


<div id="zan-bodyer">
  <div class="container">

    <div class="row">
      <div id="mainstay" class="col-md-8">
        <div class="well fade in">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <%= image_tag(current_user.avatar.url(:normal)) if current_user.avatar %>欢迎来到Wilson的个人博客 <i class="fa fa-smile-o"></i>
          <%= link_to "发帖", new_article_path, class:"btn btn-success" %>
        </div>

        <%= yield %>
      </div>

      <aside class="col-md-4" id="sidebar">
        <aside id="zan_search-2">
          <div class="search">

            <%= form_tag '/articles', method: 'get', class:"form-inline clearfix", id:"searchform"  do %>
                <%= text_field_tag :key_word, @key_word, class:"form-control", placeholder:"搜索..." %>
                <button id="search-button" class="btn btn-danger btn-small"
                        name="submit"> <i class="fa fa-search"></i></button>
            <% end %>


          </div>
        </aside>
        <aside id="zan_hotest_posts-2">


          <div class="panel panel-zan hot hidden-xs">
            <div class="panel-heading">
              <i class="fa fa-fire"></i> 最热文章 <i
            class="fa fa-times-circle panel-remove"></i> <i
            class="fa fa-chevron-circle-up panel-toggle"></i>
            </div>
            <ul class="list-group list-group-flush">
              <% @hot_articles.each do |article| %>
                  <li class="list-group-item">
                    <span class="post-title">
                       <%= link_to article_path(article), id: "myTitle" do %>
                            <%= article.title%>
                        <% end %>
                    </span>
                    <span class="badge"><%= article.view_count%></span>
                  </li>
              <% end %>
            </ul>
          </div>
        </aside>
        <aside id="zan_latest_comments-2">
          <div class="panel panel-zan hidden-xs">
            <div class="panel-heading">
              <i class="fa fa-comments"></i> 最新评论 <i
            class="fa fa-times-circle panel-remove"></i> <i
            class="fa fa-chevron-circle-up panel-toggle"></i>
            </div>
            <ul class="list-group list-group-flush">

              <% @hot_comments.each do |comment| %>
                  <li class="list-group-item"><span class="author-avatar"></span>
                    <span class="comment-log">
                        <%= link_to article_path(comment.article), id: "myTitle" do %>
                        <%= comment.body%>...
                        <% end %>
                    </span></li>
              <% end %>

            </ul>
          </div>
        </aside>
        <aside id="zan_sets-2">
          <div class="panel  panel-zan hidden-xs">
            <ul class="nav nav-pills pills-zan">
              <li class="active"><a
              href="#"
              data-toggle="tab">热门标签</a></li>
              <li></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active nav bs-sidenav fade in"
                   id="sidebar-categories">
                <% ActsAsTaggableOn::Tag.most_used.each do |tag| %>
                    <li class="cat-item cat-item-21">
                      <a href="/articles?tag=<%= tag %>"><%= tag %></a>
                    </li>
                <% end %>
              </div>
            </div>
          </div>
        </aside>
      </aside>
    </div>

  </div>
</div>

<%= render(:partial=>'footer') %>

</body>
</html>

app/views/users/shared/_links.html.erb
<div class="panel panel-zan">
  <div class="panel-heading">忘记密码？</div>
  <ul class="list-group">
    <%- if controller_name != 'sessions' %>
        <li class="list-group-item">
        <%= link_to "Log in", new_session_path(resource_name) %>
        </li>
    <% end -%>

    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
        <li class="list-group-item">
        <%= link_to "Sign up", new_registration_path(resource_name) %>
        </li>
    <% end -%>
    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
        <li class="list-group-item">
        <%= link_to "Forgot your password?", new_password_path(resource_name) %>
    <% end -%>
    <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
        <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
    <% end -%>
    <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
        <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
    <% end -%>

    <%- if devise_mapping.omniauthable? %>
        <%- resource_class.omniauth_providers.each do |provider| %>
            <li class="list-group-item">
              <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %>
            </li>
        <% end -%>
    <% end -%>
  </ul>
</div>